#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import re
import csv
from pathlib import Path
import pandas as pd

LATEX_SUBS = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}

def latex_escape(s):
    if s is None: return ""
    s = str(s).replace("\r\n", "\n").replace("\r", "\n").strip()
    s = s.replace("−", "-")
    s = "".join(LATEX_SUBS.get(ch, ch) for ch in s)
    s = s.replace("\n", r"\\ ")
    s = re.sub(r"\s{2,}", " ", s)
    return s

def sniff_delimiter(sample):
    try:
        return csv.Sniffer().sniff(sample, delimiters=";,\t|").delimiter
    except Exception:
        return ";"

def read_csv_robust(path):
    raw = path.read_text(encoding="utf-8-sig", errors="replace")
    sep = sniff_delimiter("\n".join(raw.splitlines()[:30]))
    df = pd.read_csv(path, sep=sep, engine="python", encoding="utf-8-sig")
    df = df.dropna(axis=1, how="all").fillna("").astype(str)
    df.columns = [c.strip() for c in df.columns]
    return df

def make_column_spec(ncols):
    # Wide first, last; X for the rest
    specs = ["@{}"]
    widths = [3.2] + ["X"] * (ncols-2) + [2.2]
    for w in widths:
        specs.append(rf">{{\RaggedRight\arraybackslash}}p{{{w}cm}}" if isinstance(w, float) else r">{\RaggedRight\arraybackslash}X")
    specs.append("@{}")
    return "".join(specs)

def dataframe_to_xltabular(df, caption, label, landscape):
    ncols = df.shape[1]
    colspec = make_column_spec(ncols)
    headers = [latex_escape(c) for c in df.columns]
    lines = [
        "% --- Generated by script ---", "",
        r"\small",
        r"\renewcommand{\arraystretch}{1.75}",
        r"\begin{sidewaystable}",
        r"\begin{xltabular}{\linewidth}{" + colspec + "}",
        rf"\caption{{{latex_escape(caption)}}}\label{{{latex_escape(label)}}}\\",
        r"\toprule",
        " & ".join([rf"\textbf{{{h}}}" for h in headers]) + r" \\",
        r"\midrule"
    ]
    for _, row in df.iterrows():
        lines.append(" & ".join([latex_escape(row[c]) for c in df.columns]) + r" \\")
    lines += [r"\bottomrule", r"\end{xltabular}", r"\end{sidewaystable}", ""]
    return "\n".join([l for l in lines if l])

def main():
    parser = argparse.ArgumentParser(description="Trainingsinterventionen -> LaTeX-Tabelle (xltabular, landscape)")
    parser.add_argument("csv_path", help="Path to CSV")
    parser.add_argument("-o", "--out", default="TabelleTrainingsinterventionUndReihenfolge.tex", help="TeX-Ausgabe (default: TabelleTrainingsinterventionUndReihenfolge.tex)")
    parser.add_argument("--caption", default="Trainingsinterventionen und Reihenfolgen", help="LaTeX caption")
    parser.add_argument("--label", default="tab:trainingsinterventionen", help="LaTeX label")
    parser.add_argument("--no-landscape", action="store_true", help="Kein \\begin{landscape}")
    args = parser.parse_args()

    df = read_csv_robust(Path(args.csv_path))
    tex = dataframe_to_xltabular(df, args.caption, args.label, not args.no_landscape)
    Path(args.out).write_text(tex, encoding="utf-8")
    print(f"Wrote table snippet: {Path(args.out).resolve()}")

if __name__ == "__main__":
    main()